export const allProductsArray = [
    {
      id: 1,
      imageSrc: "/all-products/Image1.png",
      title: "Nike Air Force 1 Mid '07",
      category: "Men's Shoes",
      color: "1 Colour",
      price: 10795.0,
    },
    {
      id: 2,
      imageSrc: "/all-products/Image2.png",
      title: "Nike Court Vision Low Next Nature",
      category: "Men's Shoes",
      color: "1 Colour",
      price: 4995.0,
    },
    {
      id: 3,
      imageSrc: "/all-products/Image3.png",
      title: "Nike Air Force 1 PLT.AF.ORM",
      category: "Women's Shoes",
      color: "1 Colour",
      price: 8695.0,
    },
    {
      id: 4,
      imageSrc: "/all-products/Image4.png",
      title: "Nike Air Force 1 React",
      category: "Men's Shoes",
      color: "1 Colour",
      price: 13295.0,
    },
    {
      id: 5,
      imageSrc: "/all-products/Image5.png",
      title: "Air Jordan 1 Elevate Low",
      category: "Women's Shoes",
      color: "1 Colour",
      price: 11895.0,
    },
    {
      id: 6,
      imageSrc: "/all-products/Image6.png",
      title: "Nike Standard Issue",
      category: "Women's Basketball Jersey",
      color: "1 Colour",
      price: 2895.0,
    },
    {
      id: 7,
      imageSrc: "/all-products/Image7.png",
      title: "Nike Dunk Low Retro SE",
      category: "Men's Shoes",
      color: "1 Colour",
      price: 9695.0,
    },
    {
      id: 8,
      imageSrc: "/all-products/Image8.png",
      title: "Nike Dri-FIT UV Hyverse",
      category: "Men's Short-Sleeve Graphic Fitness Top",
      color: "1 Colour",
      price: 2495.0,
    },
    {
      id: 9,
      imageSrc: "/all-products/Image9.png",
      title: "Nike Court Vision Low",
      category: "Men's Shoes",
      color: "1 Colour",
      price: 5695.0,
    },
    {
      id: 10,
      imageSrc: "/all-products/Image10.png",
      title: "Nike Dri-FIT Ready",
      category: "Men's Short-Sleeve Fitness Top",
      color: "3 Colours",
      price: 2495.0,
    },
    {
      id: 11,
      imageSrc: "/all-products/Image11.png",
      title: "Nike One Leak Protection: Period",
      category: "Women's Mid-Rise 18cm (approx.) Biker Shorts",
      color: "2 Colours",
      price: 3395.0,
    },
    {
      id: 12,
      imageSrc: "/all-products/Image12.png",
      title: "Nike Air Force 1 LV8 3",
      category: "Older Kids' Shoe",
      color: "1 Colour",
      price: 7495.0,
    },
    {
      id: 13,
      imageSrc: "/all-products/Image13.png",
      title: "Nike Blazer Low Platform",
      category: "Women's Shoes",
      color: "1 Colour",
      price: 8195.0,
    },
    {
      id: 14,
      imageSrc: "/all-products/Image14.png",
      title: "Nike Air Force 1 '07",
      category: "Women's Shoe",
      color: "2 Colours",
      price: 8195.0,
    },
    {
      id: 15,
      imageSrc: "/all-products/Image15.png",
      title: "Nike Pro Dri-FIT",
      category: "Men's Tight-Fit Sleeveless Top",
      color: "1 Colour",
      price: 1495.0,
    },
    {
      id: 16,
      imageSrc: "/all-products/Image16.png",
      title: "Nike Dunk Low Retro",
      category: "Men's Shoes",
      color: "1 Colour",
      price: 8695.0,
    },
    {
      id: 17,
      imageSrc: "/all-products/Image17.png",
      title: "Nike Air Max SC",
      category: "Women's Shoes",
      color: "1 Colour",
      price: 10795.0,
    },
    {
      id: 18,
      imageSrc: "/all-products/Image18.png",
      title: "Nike Dri-FIT UV Miler",
      category: "Men's Short-Sleeve Running Top",
      color: "1 Colour",
      price: 1695.0,
    },
    {
      id: 19,
      imageSrc: "/all-products/Image19.png",
      title: "Nike Air Max SYSTM",
      category: "Older Kids' Shoes",
      color: "1 Colour",
      price: 6495.0,
    },
    {
      id: 20,
      imageSrc: "/all-products/Image20.png",
      title: "Nike Alate All U",
      category: "Women's Light-Support Lightly Lined U-Neck Printed Sports Bra",
      color: "1 Colour",
      price: 2195.0,
    },
    {
      id: 21,
      imageSrc: "/all-products/Image21.png",
      title: "Nike Court Legacy Lift",
      category: "Women's Shoes",
      color: "2 Colours",
      price: 7495.0,
    },
    {
      id: 22,
      imageSrc: "/all-products/Image22.png",
      title: "Nike Swoosh",
      category: "Women's Medium-support Padded Sports Bra Tank",
      color: "2 Colours",
      price: 3095.0,
    },
    {
      id: 23,
      imageSrc: "/all-products/Image23.png",
      title: "Nike SB Zoom Janoski OG+",
      category: "Shoes",
      color: "1 Colour",
      price: 8595.0,
    },
    {
      id: 24,
      imageSrc: "/all-products/Image24.png",
      title: "Nike Dri-FIT Run Division Rise 365",
      category: "Men's Running Tank",
      color: "2 Colours",
      price: 3495.0,
    },
    {
      id: 25,
      imageSrc: "/all-products/Image25.png",
      title: "Nike Dri-FIT Challenger",
      category: "Men's 18cm (approx.) 2-in-1 Versatile Shorts",
      color: "1 Colour",
      price: 2495.0,
    },
    {
      id: 26,
      imageSrc: "/all-products/Image26.png",
      title: "Jordan Series ES",
      category: "Men's Shoes",
      color: "2 Colours",
      price: 7495.0,
    },
    {
      id: 27,
      imageSrc: "/all-products/Image27.png",
      title: "Nike Outdoor Play",
      category: "Older Kids' Oversized Woven Jacket",
      color: "1 Colour",
      price: 3895.0,
    },
    {
      id: 28,
      imageSrc: "/all-products/Image28.png",
      title: "Nike Sportswear Trend",
      category: "Older Kids' (Girls') High-waisted Woven Shorts",
      color: "2 Colours",
      price: 2495.0,
    },
    {
      id: 29,
      imageSrc: "/all-products/Image29.png",
      title: "Nike Blazer Low '77 Jumbo",
      category: "Women's Shoes",
      color: "1 Colour",
      price: 8595.0,
    },
    {
      id: 30,
      imageSrc: "/all-products/Image30.png",
      title: "Skate Shoe",
      category: "Men's Shoes' Shoes",
      color: "1 Colour",
      price: 5995.0,
    },
  ];